### ISSUE TITLE
Just get 20 threads of the user

### ISSUE THREAD

**Issue by juansoler** [xlysander12/InstagramDMScraper#2]
Getting the list of the user's thread just get the last 20 threads. 

I've been checking the code but it looks like it's an Instagram limitation on the API. 

Could anyone confirm that?? 

Thank you.

**Comment by xlysander12** [comment]
Hey there. It seems there's a query param "limit" you can add to the URL to get a custom number of threads and if it is not specified, the default value is 20. Since I haven't found a way to remove this limit, I've just set it to 200. Either way anyone can just change the value as needed.

If your question has been answered please let me know so I can close this issue. Thank you for contributing
